export default function Footer() {
	return (
		<footer className="border-t border-gray-200 bg-white px-4 py-6 sm:px-6 lg:px-8">
			<div className="mx-auto max-w-7xl">
				<div className="flex flex-col items-center justify-between space-y-4 sm:flex-row sm:space-y-0">
					<div className="flex items-center space-x-4">
						<svg
							className="h-8 w-8"
							viewBox="0 0 24 24"
							fill="none"
							xmlns="http://www.w3.org/2000/svg"
						>
							<title>Amazon Bedrock MCP Playground Logo</title>
							<path
								d="M12 2L2 7L12 12L22 7L12 2Z"
								stroke="currentColor"
								strokeWidth="2"
								strokeLinecap="round"
								strokeLinejoin="round"
							/>
							<path
								d="M2 17L12 22L22 17"
								stroke="currentColor"
								strokeWidth="2"
								strokeLinecap="round"
								strokeLinejoin="round"
							/>
							<path
								d="M2 12L12 17L22 12"
								stroke="currentColor"
								strokeWidth="2"
								strokeLinecap="round"
								strokeLinejoin="round"
							/>
						</svg>
						<span className="text-sm font-medium text-gray-900">Amazon Bedrock MCP Playground</span>
					</div>
				</div>
				<div className="mt-4 border-t border-gray-200 pt-4">
					<p className="text-xs text-gray-500">
						This MCP Playground is powered by Amazon Bedrock and supports Model Context Protocol (MCP) servers.
						The output generated by AI models has not been verified for accuracy and should be used responsibly.
						Please review Amazon Bedrock's{" "}
						<a className="underline text-aws-orange hover:text-aws-orange-dark" href="https://aws.amazon.com/service-terms/">
							Service Terms
						</a>{" "}
						and{" "}
						<a className="underline text-aws-orange hover:text-aws-orange-dark" href="https://aws.amazon.com/privacy/">
							Privacy Policy
						</a>
						.
					</p>
				</div>
			</div>
		</footer>
	);
}
